- name: Demo Play
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Demo Play
  hosts: localhost
  vars-files:
    - var.yml
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: URL = {{ URL }}