- name: Demo Play
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Demo Play
  hosts: localhost
  #var_files works only on play level
  vars_files:
    - var.yml
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: URL = {{ URL }}


- name: Task Level Variables
  hosts: all
  tasks:
    - name: Print Play Level Variables from files
      vars: #this vars are on;y for this task, you cannot access next task on same play
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL = {{URL}}


- name: vars from inventory
  hosts: all
  tasks:
    - name: Print Play Level Variables from files
      ansible.builtin.debug:
        msg: "URL = {{URL}}, Hostname of the sever {{ ansible_hostname }}"

- name: Register a Variable
  hosts: localhost
  tasks: 
    - name: Get uptime output
      ansible.builtin.shell: uptime
      register: out
    
    - name: Print output
      ansible.builtin.debug:
        msg: "{{ out  }}"

    - name: get facts
      ansible.builtin.set_fact:
        status: "{{ out.stdout }}"

    - name: get status
      ansible.builtin.debug:
        msg: "{{ status }}"

- name: Role Level Variables
  hosts: localhost
  roles:
    - demo